redis:
    url: ${redis.url}

server:
    port: ${server.port}
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain

logging:
    config: classpath:log4j2.xml
    base_path: ${log.base.path}
